service: default
runtime: go111

instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.6 # default value
  target_throughput_utilization: 0.6 # default value
  max_instances: 15
  min_instances: 0
  max_idle_instances: automatic  # default value
  min_idle_instances: 3
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50 # because, cloudsql2 is restricted to 60

handlers:
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /js
  static_dir: public/js

- url: /css
  static_dir: public/css

- url: /images
  static_dir: public/images

- url: /.*
  script: auto
